/**
 * Categorías (leyenda mapa) y tipos iniciales. Los tipos usan el mismo `slug` que incidentes.tipo.
 * categoria_grupo: slug de categoría (GRUPO_POR_TIPO en frontend).
 */
export const CATEGORIAS_INICIO = [
  { slug: 'hecho_vial', nombre: 'Hecho Vial', color: '#6d28d9', emergencia: 'Si', orden: 1 },
  { slug: 'incendio', nombre: 'Incendio', color: '#a21caf', emergencia: 'Si', orden: 2 },
  { slug: 'busqueda_rescate', nombre: 'Búsqueda y Rescate', color: '#4338ca', emergencia: 'Si', orden: 3 },
  { slug: 'guardia_seguridad_prevencion', nombre: 'Guardia de Seguridad y Prevención', color: '#7c2d12', emergencia: 'No', orden: 4 },
  { slug: 'condicion_arborea', nombre: 'Condición Arbórea', color: '#14532d', emergencia: 'Si', orden: 5 },
  { slug: 'solicitud_traslado', nombre: 'Solicitud de Traslado', color: '#9f1239', emergencia: 'Si', orden: 6 },
  { slug: 'clima', nombre: 'Clima', color: '#3b82f6', emergencia: 'Si', orden: 7 },
  { slug: 'hidrometeorologico', nombre: 'Hidrometeorológico', color: '#0f766e', emergencia: 'Si', orden: 8 },
  { slug: 'colapso_estructura', nombre: 'Colapso de Estructura', color: '#374151', emergencia: 'Si', orden: 9 },
  { slug: 'inspeccion_reubicacion_animal', nombre: 'Inspección y Reubicación Animal', color: '#854d0e', emergencia: 'No', orden: 10 },
  { slug: 'eliminacion_peligro', nombre: 'Eliminación de Peligro', color: '#4c1d95', emergencia: 'Si', orden: 11 },
]

export const GRUPO_POR_TIPO = {
  arrollado_peaton: 'hecho_vial',
  colision_vehiculo_moto_arrollado: 'hecho_vial',
  caida_de_nivel: 'hecho_vial',
  derrape_de_moto: 'hecho_vial',
  caida_de_vehiculo_en_marcha: 'hecho_vial',
  embarrancamiento: 'hecho_vial',
  choque_contra_objeto_fijo: 'hecho_vial',
  encunetamiento: 'hecho_vial',
  colision_con_unidad_colectiva_involucrada: 'hecho_vial',
  perdida_de_carga: 'hecho_vial',
  colision_con_vehiculo_de_carga_involucrado: 'hecho_vial',
  volcamiento_de_carga: 'hecho_vial',
  colision_entre_vehiculos: 'hecho_vial',
  volcamiento_de_unidad_colectiva: 'hecho_vial',
  colision_moto_moto: 'hecho_vial',
  volcamiento_de_vehiculo_de_carga: 'hecho_vial',
  colision_moto_bicicleta: 'hecho_vial',
  volcamiento_de_vehiculo: 'hecho_vial',
  colision_moto_vehiculo: 'hecho_vial',
  vehiculo_caido_en_cuerpo_de_agua: 'hecho_vial',
  colision_vehiculo_animal: 'hecho_vial',
  vegetacion: 'incendio',
  estructura: 'incendio',
  vehiculo_incendio: 'incendio',
  equipos_electricos: 'incendio',
  desechos_solidos: 'incendio',
  vertedero_de_basura: 'incendio',
  deflagracion: 'incendio',
  embarcacion_incendio: 'incendio',
  mat_pel: 'incendio',
  pirotecnico: 'incendio',
  persona_desaparecida_en_montana: 'busqueda_rescate',
  persona_desaparecida_en_agua: 'busqueda_rescate',
  busqueda_y_rescate_en_areas_confinadas: 'busqueda_rescate',
  rescate_en_ascensor: 'busqueda_rescate',
  rescate_de_persona_en_agua: 'busqueda_rescate',
  rescate_animal: 'busqueda_rescate',
  recuperacion_de_cadaver: 'busqueda_rescate',
  guardia_de_seguridad_y_prevencion: 'guardia_seguridad_prevencion',
  atencion_paramedica: 'guardia_seguridad_prevencion',
  atencion_medica: 'guardia_seguridad_prevencion',
  puesto_de_atencion: 'guardia_seguridad_prevencion',
  punto_de_control: 'guardia_seguridad_prevencion',
  arbol_caido_en_via_publica: 'condicion_arborea',
  arbol_caido_sobre_estructura: 'condicion_arborea',
  arbol_caido_sobre_tendido_electrico: 'condicion_arborea',
  arbol_caido_sobre_vehiculo: 'condicion_arborea',
  poda_de_arbol: 'condicion_arborea',
  arbol_en_condicion_de_riesgo: 'condicion_arborea',
  lesionado_por_caido_de_altura: 'solicitud_traslado',
  lesionado_por_arma_blanca: 'solicitud_traslado',
  lesionado_por_arma_de_fuego: 'solicitud_traslado',
  lesionado_por_descarga_electrica: 'solicitud_traslado',
  despejado: 'clima',
  nublado: 'clima',
  precipitaciones_leves: 'clima',
  precipitaciones_moderadas: 'clima',
  precipitaciones_fuertes: 'clima',
  precipitaciones_severas: 'clima',
  precipitaciones_torrenciales: 'clima',
  anegacion: 'hidrometeorologico',
  inhundacion: 'hidrometeorologico',
  desbordamiento_cano_rio_canal: 'hidrometeorologico',
  colapso_de_estructura: 'colapso_estructura',
  colapso_de_puente: 'colapso_estructura',
  enjambre_de_abejas: 'inspeccion_reubicacion_animal',
  enjambre_de_avispa: 'inspeccion_reubicacion_animal',
  serpiente: 'inspeccion_reubicacion_animal',
  alacran: 'inspeccion_reubicacion_animal',
  animal_agreste: 'inspeccion_reubicacion_animal',
  fuga_de_glp: 'eliminacion_peligro',
  derrame_de_hidrocarburo: 'eliminacion_peligro',
}

export const TIPOS_INICIO = [
  { slug: 'arrollado_peaton', nombre: 'Arrollado (Peatón)' },
  { slug: 'colision_vehiculo_moto_arrollado', nombre: 'Colisión Vehículo - Moto (Arrollado)' },
  { slug: 'caida_de_nivel', nombre: 'Caída de Nivel' },
  { slug: 'derrape_de_moto', nombre: 'Derrape de Moto' },
  { slug: 'caida_de_vehiculo_en_marcha', nombre: 'Caída de Vehículo en Marcha' },
  { slug: 'embarrancamiento', nombre: 'Embarrancamiento' },
  { slug: 'choque_contra_objeto_fijo', nombre: 'Choque contra Objeto Fijo' },
  { slug: 'encunetamiento', nombre: 'Encunetamiento' },
  { slug: 'colision_con_unidad_colectiva_involucrada', nombre: 'Colisión con Unidad Colectiva involucrada' },
  { slug: 'perdida_de_carga', nombre: 'Pérdida de Carga' },
  { slug: 'colision_con_vehiculo_de_carga_involucrado', nombre: 'Colisión con Vehículo de Carga involucrado' },
  { slug: 'volcamiento_de_carga', nombre: 'Volcamiento de Carga' },
  { slug: 'colision_entre_vehiculos', nombre: 'Colisión entre Vehículos' },
  { slug: 'volcamiento_de_unidad_colectiva', nombre: 'Volcamiento de Unidad Colectiva' },
  { slug: 'colision_moto_moto', nombre: 'Colisión Moto - Moto' },
  { slug: 'volcamiento_de_vehiculo_de_carga', nombre: 'Volcamiento de Vehículo de Carga' },
  { slug: 'colision_moto_bicicleta', nombre: 'Colisión Moto - Bicicleta' },
  { slug: 'volcamiento_de_vehiculo', nombre: 'Volcamiento de Vehículo' },
  { slug: 'colision_moto_vehiculo', nombre: 'Colisión Moto - Vehículo' },
  { slug: 'vehiculo_caido_en_cuerpo_de_agua', nombre: 'Vehículo caído en cuerpo de agua (caño, río, canal)' },
  { slug: 'colision_vehiculo_animal', nombre: 'Colisión Vehículo - Animal' },
  { slug: 'vegetacion', nombre: 'Vegetación' },
  { slug: 'estructura', nombre: 'Estructura' },
  { slug: 'vehiculo_incendio', nombre: 'Vehículo' },
  { slug: 'equipos_electricos', nombre: 'Equipos eléctricos' },
  { slug: 'desechos_solidos', nombre: 'Desechos sólidos' },
  { slug: 'vertedero_de_basura', nombre: 'Vertedero de basura' },
  { slug: 'deflagracion', nombre: 'Deflagración' },
  { slug: 'embarcacion_incendio', nombre: 'Embarcación' },
  { slug: 'mat_pel', nombre: 'Mat-Pel' },
  { slug: 'pirotecnico', nombre: 'Pirotécnico' },
  { slug: 'persona_desaparecida_en_montana', nombre: 'Persona desaparecida en montaña' },
  { slug: 'persona_desaparecida_en_agua', nombre: 'Persona desaparecida en agua' },
  { slug: 'busqueda_y_rescate_en_areas_confinadas', nombre: 'Búsqueda y Rescate en áreas confinadas' },
  { slug: 'rescate_en_ascensor', nombre: 'Rescate en ascensor' },
  { slug: 'rescate_de_persona_en_agua', nombre: 'Rescate de persona en agua' },
  { slug: 'rescate_animal', nombre: 'Rescate animal' },
  { slug: 'recuperacion_de_cadaver', nombre: 'Recuperación de cadáver' },
  { slug: 'guardia_de_seguridad_y_prevencion', nombre: 'Guardia de Seguridad y Prevención' },
  { slug: 'atencion_paramedica', nombre: 'Atención paramédica' },
  { slug: 'atencion_medica', nombre: 'Atención médica' },
  { slug: 'puesto_de_atencion', nombre: 'Puesto de Atención' },
  { slug: 'punto_de_control', nombre: 'Punto de Control' },
  { slug: 'arbol_caido_en_via_publica', nombre: 'Árbol caído en vía pública' },
  { slug: 'arbol_caido_sobre_estructura', nombre: 'Árbol caído sobre estructura' },
  { slug: 'arbol_caido_sobre_tendido_electrico', nombre: 'Árbol caído sobre tendido eléctrico' },
  { slug: 'arbol_caido_sobre_vehiculo', nombre: 'Árbol caído sobre vehículo' },
  { slug: 'poda_de_arbol', nombre: 'Poda de árbol' },
  { slug: 'arbol_en_condicion_de_riesgo', nombre: 'Árbol en condición de riesgo' },
  { slug: 'lesionado_por_caido_de_altura', nombre: 'Lesionado por caída de altura' },
  { slug: 'lesionado_por_arma_blanca', nombre: 'Lesionado por arma blanca' },
  { slug: 'lesionado_por_arma_de_fuego', nombre: 'Lesionado por arma de fuego' },
  { slug: 'lesionado_por_descarga_electrica', nombre: 'Lesionado por descarga eléctrica' },
  { slug: 'despejado', nombre: 'Despejado', color: '#ffffff' },
  { slug: 'nublado', nombre: 'Nublado', color: '#9ca3af' },
  { slug: 'precipitaciones_leves', nombre: 'Precipitaciones leves', color: '#3b82f6' },
  { slug: 'precipitaciones_moderadas', nombre: 'Precipitaciones moderadas', color: '#84cc16' },
  { slug: 'precipitaciones_fuertes', nombre: 'Precipitaciones fuertes', color: '#facc15' },
  { slug: 'precipitaciones_severas', nombre: 'Precipitaciones severas', color: '#d97706' },
  { slug: 'precipitaciones_torrenciales', nombre: 'Precipitaciones torrenciales', color: '#dc2626' },
  { slug: 'anegacion', nombre: 'Anegación' },
  { slug: 'inhundacion', nombre: 'Inundación' },
  { slug: 'desbordamiento_cano_rio_canal', nombre: 'Desbordamiento (caño, río, canal)' },
  { slug: 'colapso_de_estructura', nombre: 'Colapso de estructura' },
  { slug: 'colapso_de_puente', nombre: 'Colapso de puente' },
  { slug: 'enjambre_de_abejas', nombre: 'Enjambre de abejas' },
  { slug: 'enjambre_de_avispa', nombre: 'Enjambre de avispa' },
  { slug: 'serpiente', nombre: 'Serpiente' },
  { slug: 'alacran', nombre: 'Alacrán' },
  { slug: 'animal_agreste', nombre: 'Animal agreste' },
  { slug: 'fuga_de_glp', nombre: 'Fuga de GLP' },
  { slug: 'derrame_de_hidrocarburo', nombre: 'Derrame de hidrocarburo' },
]